[env:blink_rgb]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.arduino.memory_type = opi_opi
build_src_filter = +<blink_rgb.cpp>

lib_deps =
    adafruit/Adafruit NeoPixel

[env:blink_led]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.arduino.memory_type = opi_opi
build_src_filter = +<blink_led.cpp>

lib_deps =
    adafruit/Adafruit NeoPixel