[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.arduino.memory_type = opi_opi

lib_deps =
    adafruit/Adafruit NeoPixel